"""Core data models for orders, fills, and market data."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class Side(StrEnum):
    """Order side."""

    BUY = "BUY"
    SELL = "SELL"

    def opposite(self) -> Side:
        return Side.SELL if self is Side.BUY else Side.BUY


class OrderType(StrEnum):
    """Order execution style."""

    MARKET = "MARKET"
    LIMIT = "LIMIT"


class Bar(BaseModel):
    """A single OHLCV bar."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    timestamp: datetime
    open: float = Field(..., gt=0)
    high: float = Field(..., gt=0)
    low: float = Field(..., gt=0)
    close: float = Field(..., gt=0)
    volume: float = Field(..., ge=0)


class Order(BaseModel):
    """An intent to trade, generated by a strategy."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    side: Side
    quantity: float = Field(..., gt=0)
    order_type: OrderType = OrderType.MARKET
    limit_price: float | None = Field(default=None, gt=0)
    timestamp: datetime


class Fill(BaseModel):
    """Result of an executed order, including costs."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    side: Side
    quantity: float = Field(..., gt=0)
    price: float = Field(..., gt=0)
    fee: float = Field(..., ge=0)
    timestamp: datetime

    @property
    def notional(self) -> float:
        """Signed notional value of the fill."""
        sign = 1.0 if self.side is Side.BUY else -1.0
        return sign * self.price * self.quantity


class Position(BaseModel):
    """Net position in a single symbol."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    quantity: float = 0.0
    avg_price: float = 0.0

    @property
    def is_flat(self) -> bool:
        return abs(self.quantity) < 1e-12
